/* errno is not a global variable, because that would make using it
   non-reentrant.  Instead, its address is returned by the function
   __errno.  */

#ifndef _PRJ_CONFIG_H_
#define _PRJ_CONFIG_H_

#ifdef __cplusplus
extern "C" {
#endif

#define CONFIG_BLE_ADV_USE_WHITELIST 0
#define CONFIG_BLE_ADV_RESTART_ON_DISCONNECT 1
#define CONFIG_BLE_ADV_EXTENDED_ADVERTISING 0
#define CONFIG_BLE_ADV_NAME "nRF_BM_LBS"
#define CONFIG_BLE_ADV_DIRECTED_ADVERTISING 0
#define CONFIG_BLE_ADV_USE_WHITELIST 0
//#define CONFIG_BLE_ADV_PRIMARY_PHY_AUTO 1
#define CONFIG_BLE_ADV_PRIMARY_PHY 0x00
//#define CONFIG_BLE_ADV_SECONDARY_PHY_AUTO 1
#define CONFIG_BLE_ADV_SECONDARY_PHY 0x00
#define CONFIG_BLE_ADV_DIRECTED_ADVERTISING_HIGH_DUTY 0
#define CONFIG_BLE_ADV_DIRECTED_ADVERTISING 0
#define CONFIG_BLE_ADV_FAST_ADVERTISING 1
#define CONFIG_BLE_ADV_SLOW_ADVERTISING 1
#define CONFIG_BLE_ADV_FAST_ADVERTISING_TIMEOUT 1000
#define CONFIG_BLE_ADV_FAST_ADVERTISING_INTERVAL 32
#define CONFIG_BLE_ADV_SLOW_ADVERTISING_TIMEOUT 18000
#define CONFIG_BLE_ADV_SLOW_ADVERTISING_INTERVAL 64

#define CONFIG_BLE_CONN_PARAMS_ATT_MTU 23

#define CONFIG_BLE_CONN_PARAMS_MIN_CONN_INTERVAL 6
#define CONFIG_BLE_CONN_PARAMS_MAX_CONN_INTERVAL 256
#define CONFIG_BLE_CONN_PARAMS_PERIPHERAL_LATENCY 0
#define CONFIG_BLE_CONN_PARAMS_SUP_TIMEOUT 100
#define CONFIG_BLE_CONN_PARAMS_NEGOTIATION_RETRIES 2
#define CONFIG_BLE_CONN_PARAMS_MAX_PERIPHERAL_LATENCY_DEVIATION 0
#define CONFIG_BLE_CONN_PARAMS_MAX_SUP_TIMEOUT_DEVIATION 400
#define CONFIG_BLE_CONN_PARAMS_DISCONNECT_ON_FAILURE 0

//data_length.c
#define CONFIG_BLE_CONN_PARAMS_DATA_LENGTH_TX 27
#define CONFIG_BLE_CONN_PARAMS_DATA_LENGTH_RX 27
//phy_mode.c
#define CONFIG_BLE_CONN_PARAMS_PHY 0x00
#define CONFIG_NRF_SDH_BLE_GAP_EVENT_LENGTH 3

//dis.c
#define CONFIG_BLE_DIS_CHAR_SEC_MODE 0x11
#define CONFIG_BLE_DIS_MANUFACTURER_NAME "Nordic Semiconductor"
#define CONFIG_BLE_DIS_MODEL_NUMBER "nrf54l15"
#define CONFIG_BLE_DIS_SERIAL_NUMBER "ABCD"
#define CONFIG_BLE_DIS_HW_REVISION "hw 54.15.0"
#define CONFIG_BLE_DIS_FW_REVISION "fw 17.2.0"
#define CONFIG_BLE_DIS_SW_REVISION "sw 1.0.0"

#define CONFIG_NRF_SDH_BLE_CONN_TAG 99
#define CONFIG_BLE_ADV_NAME "nRF_BM_LBS"
#ifdef __cplusplus
}
#endif
#endif /* _PRJ_CONFIG_H_ */
